plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "main"

exclude:
  - "*.config.js"
  - "package*.json"
  - assets
  - _data/manifest.yml
  - node_modules
  - CNAME
  - "Gemfile*"
  - ".idea"

url: https://php-flasher.io

highlighter: none
