url: https://php-flasher.io

title: PHPFlasher

logo: https://php-flasher.io/dist/images/php-flasher-logo.png

author:
  name: Younes KHOUBZA
  twitter: yoeunes
  url: https://www.linkedin.com/in/younes-khoubza/
  picture: https://media.licdn.com/media/AAYQAQSOAAgAAQAAAAAAAB-zrMZEDXI2T62PSuT6kpB6qg.png

image:
  path: https://php-flasher.io/dist/images/php-flasher-logo.png
  alt: PHPFlasher Logo

twitter:
  username: phpflasher
  image: https://php-flasher.io/dist/images/php-flasher-logo.png
  card: https://php-flasher.io/dist/images/php-flasher-logo.png

social:
    name: phpflasher
    links:
        - https://twitter.com/phpflasher
        - https://github.com/php-flasher
        - https://twitter.com/yoeunes
        - https://github.com/yoeunes
        - https://www.linkedin.com/in/younes-khoubza/

highlighter: none

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "main"
      image: https://php-flasher.io/dist/images/php-flasher-logo.png

exclude:
  - "*.config.js"
  - "package*.json"
  - assets
  - _data/manifest.yml
  - node_modules
  - CNAME
  - "Gemfile*"
  - ".idea"
