url: https://php-flasher.io

title: PHPFlasher

logo: https://php-flasher.io/dist/images/php-flasher-social-card.png

author:
  name: Younes KHOUBZA
  twitter: yoeunes
  url: https://www.linkedin.com/in/younes-khoubza/
  picture: https://php-flasher.io/dist/images/php-flasher-social-card.png

image:
  path: https://php-flasher.io/dist/images/php-flasher-social-card.png
  alt: PHPFlasher

twitter:
  username: phpflasher
  image: https://php-flasher.io/dist/images/php-flasher-social-card.png
  card: summary_large_image

social:
    name: phpflasher
    links:
        - https://twitter.com/phpflasher
        - https://github.com/php-flasher
        - https://twitter.com/yoeunes
        - https://github.com/yoeunes
        - https://www.linkedin.com/in/younes-khoubza/

highlighter: none

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      layout: "main"
      image: https://php-flasher.io/dist/images/php-flasher-social-card.png

exclude:
  - "*.config.js"
  - "package*.json"
  - assets
  - _data/manifest.yml
  - node_modules
  - CNAME
  - "Gemfile*"
  - ".idea"
