plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      published_at: "2020-11-28"
      updated_at: "2022-05-08"

exclude:
  - "*.config.js"
  - "package*.json"
  - "assets"
  - "node_modules"
  - "Gemfile*"
  - ".idea"

url: https://php-flasher.io
